---
title: "overview"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{overview}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

# Package overview

The  this package has been designed and are maintained by [BioCelerate](https://transceleratebiopharmainc.com/biocelerate/) in collaboration with [phuse nonclinical topics working group](https://www.phusewiki.org/wiki/index.php?title=Nonclinical_Topics_Working_Group).

If you have questions or you're interested in contributing to the scripts, please contact any of the GitHub contributors listed on the right of this page.   


# Getting started

## Dependencies 

The scripts in this repository reply on the following external packages that need to be installed into the R programming environment:

* data.table
* data.table,
* readxl,
* magrittr,
* xfun,
* stringr,
* DBI,
* DescTools,
* parsedate
* RSQLite or ROracle

## Configuration

bla bla bla



## Function overview.

The following functions for querying the  SEND database. Further documentation and usage can be found within each module. 
...



